train_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: /mnt2/dataset/12119cell-20211219-6/all_realign_488_3x3/ # the input lf path
      root_path_2: /mnt2/dataset/12119cell-20211219-6/all_realign_488_3x3_M72_psrecon/ # the volume reconstructed or paired from lf
      repeat: 10
      first_k: 9
      last_k: 9
      cache: in_memory
  wrapper:
    name: rlfm-vcdnet
    args:
      inp_size: 192
      volume_depth : 101
      # scale_max: 4
      # augment: true
      # sample_q: 2304
  batch_size: 1

val_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: /mnt2/dataset/12119cell-20211219-6/all_realign_488_3x3/
      root_path_2: /mnt2/dataset/12119cell-20211219-6/all_realign_488_3x3_M72_psrecon/
      repeat: 1
      first_k: 10
      last_k: 1
      cache: in_memory
  wrapper:
    name: rlfm-vcdnet
    args:
      inp_size: 192
      volume_depth : 101
      # scale_max: 4
      # sample_q: 2304
  batch_size: 1

# data_norm:
#   inp: {sub: [0.5], div: [0.5]}
#   gt: {sub: [0.5], div: [0.5]}

model:
  name: rlfm
  args:
    encoder_spec:
      name: vsreconnet
      args:
        inChannels : 169
        outChannels : 101
    # imnet_spec:
    #   name: mlp
    #   args:
    #     out_dim: 3
    #     hidden_list: [256, 256, 256, 256]

optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 400
# multi_step_lr:
#   milestones: [40, 80, 120, 160]
#   gamma: 0.5

loss_fn: 'nn.MSELoss()'

epoch_val: 1
epoch_save: 100